### ISSUE TITLE
PHP 8.3 errors or so

### ISSUE THREAD

**Issue by TheFrozenThr0ne** [azerothcore/playermap#11]
I got this errors im on php 8.3.x

Not sure if misconfigured or not compatible dont know.

Warning: Undefined array key 4 in C:\laragon\www\...\playermap\pomm_conf.php on line 26

Warning: Trying to access array offset on null in C:\laragon\www\...\playermap\pomm_conf.php on line 26

Warning: Undefined array key 4 in C:\laragon\www\...\playermap\pomm_conf.php on line 27

Warning: Trying to access array offset on null in C:\laragon\www\...\playermap\pomm_conf.php on line 27

Warning: Undefined array key 4 in C:\laragon\www\...\playermap\pomm_conf.php on line 29

Warning: Trying to access array offset on null in C:\laragon\www\...\playermap\pomm_conf.php on line 29

Warning: Undefined array key 4 in C:\laragon\www\...\playermap\pomm_conf.php on line 30

Warning: Trying to access array offset on null in C:\laragon\www\...\playermap\pomm_conf.php on line 30

Warning: Undefined array key 4 in C:\laragon\www\...\playermap\pomm_conf.php on line 31

Warning: Trying to access array offset on null in C:\laragon\www\...\playermap\pomm_conf.php on line 31

Warning: Undefined array key 4 in C:\laragon\www\...\playermap\pomm_conf.php on line 32

Warning: Trying to access array offset on null in C:\laragon\www\...\playermap\pomm_conf.php on line 32

**Comment by xengine-qyt** [comment]
work fine on my ubuntu24.04 with php8.3

**Comment by Helias** [comment]
review properly your conf files checking if some parameters are missing
