### ISSUE TITLE
Does not work when the server is not on a standard port

### ISSUE THREAD

**Issue by leewheel** [azerothcore/playermap#12]
if my realmd port is 3726 and game port is 8098 then i config the php
`$server[1]['addr']          = '127.0.0.1'; 

$server[1]['addr_wan']      = 'wow.Mywowo.fun'; 

$server[1]['game_port']     =  8098;       

$server[1]['rev']           = '';        

$server[1]['both_factions'] =  true;    

or 
`$server[1]['addr']          = '127.0.0.1'; 

$server[1]['addr_wan']      = 'wow.Mywowo.fun:3726'; 

$server[1]['game_port']     =  8098;  

$server[1]['rev']           = ''; 

$server[1]['both_factions'] =  true; `

both do not work, so how can i get it work?

![image](https://github.com/user-attachments/assets/7da4609b-3615-43a2-9b78-7782226cbaf3)

**Comment by Helias** [comment]
We used this on azerothcore, it should also work with tbcmangos but I am not sure what is going on on your setup, check all the parameters and double check the related table used with your database

**Comment by leewheel** [comment]
I see, maybe need change Database Sql read statement ,thanks!
