### ISSUE TITLE
How do I use this web page? What are the required runtime environments? Can you provide a more detailed explanation?

### ISSUE THREAD

**Issue by 1825679767** [azerothcore/playermap#6]
Spent a lot of time, but still failed to set it up. Can you share a more detailed tutorial?

**Comment by willowweevil** [comment]
@1825679767 
You should add correct credentials of databases in playermap_config.php and write correct realm_id in pomm_conf.php. 
Then you can start the application with command "php -S <IP_address>:<web_page_PORT>"

**Comment by Helias** [comment]
as written in the [readme](https://github.com/azerothcore/playermap#configure), you have to configure those two files and then start the application through a web server which interprets PHP or with the command that @willowweevil showed above
