### ISSUE TITLE
query

### ISSUE THREAD

**Issue by zxnhrdz** [azerothcore/playermap#8]
This feature is not supported on ubuntu systems? Keeps showing empty maps!

![image](https://github.com/azerothcore/playermap/assets/110412571/3ab93c2f-a29b-475a-a6db-ac7929e95096)

**Comment by Helias** [comment]
Hi, it works on Ubuntu, you probably miss some configuration in `config/playermap_config.php.`

**Comment by virgo77** [comment]
Hi!
I'm afraid he's right.

My SQL Server is reachable on this IP Address: 192.168.1.250:3306
The "Auth DB" name is: `azerothcore_auth`
The "Characters DB" name is: `azerothcore.original_characters`
The "World DB" name is: `azerothcore.playerbots.spp_world`

The RealmID of my running server is: `9`
The server is reachable on port: `8089`
![image](https://github.com/azerothcore/playermap/assets/23108339/29b3e382-b8fc-4a9f-a5d6-8233c8e65125)


I configured the `./config/playermap_config.php`:
![image](https://github.com/azerothcore/playermap/assets/23108339/87878688-3507-4772-8ee6-028f9c2b8f71)


Then I configured `./pomm_config.php` with the RealmID:
![image](https://github.com/azerothcore/playermap/assets/23108339/b5db4cd2-1806-485e-8163-c7a7dcb9635c)


And...:
![image](https://github.com/azerothcore/playermap/assets/23108339/7d236066-5e20-4b17-9459-cadc578e2509)


The server where the 'playermap' is hosted can ping both these IP Addresses:
- 192.168.1.250 (MariaDB Server)
- 192.168.0.236 (where 'authserver' and 'worldserver' runs and are reachable)
![image](https://github.com/azerothcore/playermap/assets/23108339/b3818efe-0bfc-4c97-ae5b-70c4d9ee5e2e)


Just about the 'playermap_config.php', it is said the "db_type = mysql". If running MariaDB, should it be changed?

About my configuration:
- Debian 11 Bullseye, x64
- nginx + SSL
- php-8.3 (FileInfo / fpm / gd / gmp / Mbstring / Mysqli / Mysqlnd / SimpleXML)
-  MariaDB 10.6.18

Thanks for your help :)

Regards,
V.

**Comment by Helias** [comment]
not sure what you are doing wrong, I know that the playermap config are not easy to set, the best way to solve this is debugging the issue, try to print everything enabling the errors/warnings using the following code in the top of index.php
```PHP
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);
```
[[source]](https://stackoverflow.com/questions/1053424/how-do-i-get-php-errors-to-display)

**Comment by virgo77** [comment]
Hi!
There's no onscreen output :(

I enabled the `display_errors = On` in my `/etc/php/8.3/fpm/php.ini` file, then restarted nginx and still no results

**Comment by virgo77** [comment]
ok so I got news... it's a PHP issue!

In fact, PlayerMap works at least with PHP7.4 / PHP8.0, but not with PHP8.1/2/3

With PHP7.4 / PHP8.0, the index can show the players, even if they are bots.
But with PHP8.1/2/3, the playermap is unable to work

So, as your code is not updated since 4 years, do you think you can update it and make it working with recent PHP versions?

Thanks a lot.

Best Regards,
V.

**Comment by virgo77** [comment]
PHP 8.0.30:

![image](https://github.com/azerothcore/playermap/assets/23108339/1a07035a-b80b-440c-9acc-c59c2dd5ef90)

**Comment by Bladeage** [comment]
Thanks to @virgo77 for pointing out the PHP version error.
Unfortuantely I am not capable of solving this compatibility issue.
Although I found an easy way to make the playermap work with docker.

Start up a docker-compose.yml like:

`version: "2.1"

services:
  nginx-wow-map:
    container_name: nginx-wow-map
    image: ghcr.io/linuxserver/nginx:1.20.2-r1-ls203 
    volumes:
      - /your-nginx-directory:/config
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped`

Change your ports and volume to whatever you like.
The version this compose (nginx:1.20.2-r1-ls203) pulls is the last Nginx version that supports PHP 8.0.
After that just drop the contents of the playermap Github into the www/ folder and remember to adapt your .conf

I also let AI translate the zones and player information into german and made it available on a [fork of playermap](https://github.com/Bladeage/playermap).
For the language changing just change this line in 'index.php' and 'pomm_play.php':
'require_once("map_german.php");'

<img width="781" alt="example-german" src="https://github.com/user-attachments/assets/705ef753-2423-4845-bbc0-7f15755b8fba">

**Comment by Helias** [comment]
we should implement a proper translation system in this software
about the docker container, you could add the docker-compose file in the repository through a Pull Request

p.s. thanks for all the feedbacks!

**Comment by Helias** [comment]
thanks to https://github.com/azerothcore/playermap/pull/9 playermap now should be supported by PHP 8.1+
We could even close this issue I think
